# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /rasa

# install dependencies
RUN pip install rasa==2.3.4

# copy the content of the local src directory to the working directory
COPY . .

# command to run on container start
CMD [ "rasa", "run", "--enable-api" ]

EXPOSE 5005/tcp